apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-storage-writer
  name: location-storage-writer
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30003
  selector:
    service: location-storage-writer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-storage-writer
  name: location-storage-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-storage-writer
  template:
    metadata:
      labels:
        service: location-storage-writer
    spec:
      containers:
      - image: alimahmoudhabib85/nd064-location-storage-writer:latest
        name: location-storage-writer
        imagePullPolicy: Always
      restartPolicy: Always
