# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x05unary\"I\n\x0fLocationRequest\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\t2Q\n\x15LocationStorageWriter\x12\x38\n\x06\x43reate\x12\x16.unary.LocationRequest\x1a\x16.unary.LocationRequestb\x06proto3')



_LOCATIONREQUEST = DESCRIPTOR.message_types_by_name['LocationRequest']
LocationRequest = _reflection.GeneratedProtocolMessageType('LocationRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONREQUEST,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:unary.LocationRequest)
  })
_sym_db.RegisterMessage(LocationRequest)

_LOCATIONSTORAGEWRITER = DESCRIPTOR.services_by_name['LocationStorageWriter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONREQUEST._serialized_start=25
  _LOCATIONREQUEST._serialized_end=98
  _LOCATIONSTORAGEWRITER._serialized_start=100
  _LOCATIONSTORAGEWRITER._serialized_end=181
# @@protoc_insertion_point(module_scope)
