##Following the officail documentian of Docker https://docs.docker.com/ci-cd/github-actions/
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2 
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push frontend
        uses: docker/build-push-action@v2.8.0
        with: 
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nd064-udaconnect-app:latest
          context: "{{defaultContext}}:modules/frontend"
          file: ./Dockerfile
          push: true
      -
        name: Build and push API
        uses: docker/build-push-action@v2.8.0
        with:
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nd064-udaconnect-app:latest
          context: "{{defaultContext}}:modules/api"
          file: ./Dockerfile
          push: true
      -
        name: Build and push locations-api
        uses: docker/build-push-action@v2.8.0
        with:
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nd064-locations-api:latest 
          context: "{{defaultContext}}:modules/locations-api"
          file: ./Dockerfile
          push: true
          
