##Following the officail documentian of Docker https://docs.docker.com/ci-cd/github-actions/
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2 
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push frontend
        uses: docker/build-push-action@v2.8.0
        with: 
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nd064-udaconnect-app:latest
          context: "{{defaultContext}}:modules/frontend"
          file: ./Dockerfile
          push: true
      -
        name: Build and push person-storage-writer
        uses: docker/build-push-action@v2.8.0
        with:
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nd064-person-storage-writer:latest
          context: "{{defaultContext}}:modules/person-storage-writer"
          file: ./Dockerfile
          push: true
      -
        name: Build and push person-storage-service
        uses: docker/build-push-action@v2.8.0
        with:
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nd064-person-storage-service:latest
          context: "{{defaultContext}}:modules/person-storage-service"
          file: ./Dockerfile
          push: true
      -
        name: Build and push location-storage-service
        uses: docker/build-push-action@v2.8.0
        with:
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nd064-location-storage-service:latest
          context: "{{defaultContext}}:modules/location-storage-service"
          file: ./Dockerfile
          push: true
      -
        name: Build and push location-storage-writer
        uses: docker/build-push-action@v2.8.0
        with:
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nd064-location-storage-writer:latest 
          context: "{{defaultContext}}:modules/location-storage-writer"
          file: ./Dockerfile
          push: true
      -
        name: Build and push location-storage-consumer
        uses: docker/build-push-action@v2.8.0
        with:
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nd064-location-storage-consumer:latest 
          context: "{{defaultContext}}:modules/location-storage-consumer"
          file: ./Dockerfile
          push: true
          
